#!/usr/bin/env bash

case "$BLOCK_BUTTON" in
  1)
    if [ -z "$UPDATE_CMD" ]; then
      echo "UPDATE_CMD not set!"
      exit 1
    fi
    UPDATE_CMD=$(echo "$UPDATE_CMD" | sed -E "s/^['\"](.*)['\"]$/\1/")
    i3-msg -q exec "$(eval "$UPDATE_CMD")"
    ;;
esac

if [ ! -x "$(command -v checkupdates)" ]; then
  echo 'checkupdates not found, install pacman-contrib'
  exit 1
fi

until curl --output /dev/null --silent --head --fail google.com; do
  sleep 5
done

NUM=$(checkupdates | wc -l)

if [ "$AUR" == "true" ]; then
  if [ ! -x "$(command -v paru)" ]; then
    echo 'paru not found'
    exit 1
  fi

  NUM=$(("$NUM" + $(paru -Qua | wc -l)))
fi

# if [ "$NUM" -ne 0 ]; then
  echo " $NUM"
# fi
