#!/usr/bin/env bash

if [ ! -x "$(command -v dunstctl)" ]; then
  echo 'dunstctl not found, install dunst-git'
  exit 1
fi

DUNST_DISPLAY_FILE="/tmp/I3_BAR_DUNST_DISPLAY"

case "$BLOCK_BUTTON" in
  1) dunstctl set-paused toggle ;;
  3)
    if [ -f "$DUNST_DISPLAY_FILE" ]; then
      dunstctl close-all
      rm "$DUNST_DISPLAY_FILE" &>/dev/null
    else
      for _ in {1..10}; do
        dunstctl history-pop
      done
      touch "$DUNST_DISPLAY_FILE" &>/dev/null
    fi
    ;;

esac

case "$(dunstctl is-paused)" in
  "false") echo "<span size='xx-small'> </span><span> </span>" ;;
  "true") echo "<span size='xx-small'> </span><span color=\"#aaaaaa\"> </span>" ;;
  *) echo "error connecting to dunstctl" ;;
esac
