#!/usr/bin/env bash

STR=""

if xset -q | grep -E 'Caps Lock:\s+on' &>/dev/null; then
  STR+="<span color=\"#FFA51F\"></span>"
fi

if xset -q | grep -E 'Num Lock:\s+on' &>/dev/null; then
  STR+="<span color=\"#BB4EFF\">  </span>"
fi

if [ -n "$STR" ]; then
  echo "$STR"
fi
