#!/usr/bin/env bash

if [ ! -x "$(command -v nvidia-smi)" ]; then
  echo "nvidia-smi not found"
  exit 1
fi

TEMP=$(nvidia-smi | grep -oE '[0-9]+C' | sed 's/C$//')

if [ "$TEMP" -le 65 ]; then
  COLOR="#00ff1e"
elif [ "$TEMP" -le 75 ]; then
  COLOR="#ffff00"
else
  COLOR="#ff4d2e"
fi

TEMP="<span color=\"$COLOR\">$TEMP°</span>"

echo " $TEMP"
